[workspace]
members = [
  "crates/gamacros-controller",
  "crates/gamacrosd",
  "crates/gamacros-profile",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
homepage = "https://github.com/mishamyrt/gamacross"
documentation = "https://github.com/mishamyrt/gamacros"
repository = "https://github.com/mishamyrt/gamacros"
authors = ["Mikhael Khrustik <misha@myrt.co>"]
license = "MIT"

[workspace.dependencies]
gamacrosd = { path = "crates/gamacrosd" }
gamacros-keypress = { path = "crates/gamacros-keypress" }
gamacros-controller = { path = "crates/gamacros-controller" }
gamacros-activity = { path = "crates/gamacros-activity" }
gamacros-profile = { path = "crates/gamacros-profile" }

tokio = { version = "1", optional = false, features = ["full"] }
async-recursion = { version = "1.0.2", optional = false }
thiserror = "2.0.12"
lru = "0.14.0"

once_cell = "1.21.3"

libc = "0.2.172"

enigo = { version = "0.5.0" }
image = { version = "0.25.1", default-features = false, features = [
  "bmp",
  "jpeg",
] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34+deprecated"
serde_derive = "1.0.219"
plist = "1.7.1"

log = "0.4.26"
colored = "3.0.0"
fern = "0.6.1"

objc = "0.2.7"
cocoa = "0.24.1"

# Dev dependencies
rand = "0.9.1"
