# TODO: Move to Cargo.toml

[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
# The installers to generate for each app
installers = []
build-command = ["just build"]
github-build-setup = "../build-setup.yaml"

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"

[dist.dependencies.homebrew]
sdl2 = { version = "2.32.8" }
pkg-config = { version = "0.29.3" }
just = { version = "1.42.4" }
