[package]
name = "gamacros-bit-derive"
version = "0.0.0"
edition = { workspace = true }
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
gamacros-bit-mask = { workspace = true }
