name: Benchmark

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  JUST_VERSION: "1.42.4"

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Setup sdl2
        run: |
          brew install sdl2 pkg-config
          echo "RUSTFLAGS=-L native=/opt/homebrew/lib -C link-args=-Wl,-rpath,/opt/homebrew/lib" >> $GITHUB_ENV

      - name: Setup Just
        uses: extractions/setup-just@v3
        with:
          just-version: ${{ env.JUST_VERSION }}

      - name: Build benchmarks
        run: cargo codspeed build

      - name: Run the benchmarks
        run: cargo codspeed run
        # uses: CodSpeedHQ/action@v3
        # with:
        #   run: cargo codspeed run
        #   token: ${{ secrets.CODSPEED_TOKEN }}
