name: Benchmark

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  JUST_VERSION: "1.42.4"

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Setup sdl2
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev

      - name: Build benchmarks
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
