name: Quality Assurance

on:
  push:

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install SDL2 with build dependencies
        run: brew install sdl2 pkg-config
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Collect coverage data
        run: |
          export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"
          cargo llvm-cov nextest

  code-style:
    name: Code style check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Check clippy
        run: cargo clippy
